vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.ignorecase = false
vim.o.number = true
vim.o.hidden = true
vim.o.completeopt = "menuone,noinsert,noselect"
vim.o.showmode = false
vim.o.foldmethod="indent"
vim.o.foldlevel=99
vim.o.autochdir=true
vim.o.splitright=true
vim.o.splitbelow=true
