#!/bin/bash
shopt -s globstar

function help() {
	printf "Usage: %s [args] [path]...\n" "$(basename "$0")"
	printf "Hardlink dotfiles to repository\n"
	printf "It is meant to be run from the repository root directory\n"
	printf "\n"
	printf "  -t target_dir  Target directory\n"
	printf "  -f             Add --force flag when creating hardlink\n"
	printf "\n"
	printf "If -t flag is not passed, the target path structure is dotfiles_dir/source_path.trim_prefix(home_dir)"
	printf "\n"
	printf "Example: %s /home/<user>/.config/nvim\n" "$(basename "$0")"
	exit 0
}

function run() {
	dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	[[ $# -ge 1 ]] || {
		help
		exit 1
	}
	sources=()
	while [[ "$1" != "" ]]; do
		local arg="$1"
		if [[ "$arg" == "-h" ]]; then
			help
		elif [[ "$arg" == "-t" ]]; then
			[[ -z "${all_target_dir+x}" ]] || {
				printf "ERROR: target directory already set\n"
				exit 1
			}
			all_target_dir="$2"
			shift 2
		elif [[ "$arg" == "-f" ]]; then
			lnargs=("$arg")
			shift
		elif [[ -d "$arg" ]]; then
			sources+=("$arg"/**/*)
			shift
		else
			[[ -e "$arg" ]] || {
				printf "ERROR: path '%s' does not exist\n" "$arg"
				exit 1
			}
			sources+=("$arg")
			shift
		fi
	done
	for source in "${sources[@]}"; do
		source=$(readlink -f "${source}")
		if [[ -n "${all_target_dir+x}" ]]; then
			target_dir="${all_target_dir}"
		else
			target_dir="${dotfiles_dir}/$(dirname "${source#$HOME/}")"
		fi
		printf "\033[0;32m%s <- %s\033[0m\n" "${source}" "${target_dir}"
		mkdir -p "${target_dir}" && ln "${lnargs[@]}" "${source}" "${target_dir}"
	done
}

run "$@"
