shell = "zsh"

[templates]
defer = """{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}"""

# completions

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# sourced

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.pure]
# github = "rossmacarthur/pure"
local = "~/.config/zsh/plugins/pure"
use = ["{async,pure}.zsh"]

# deferred

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.bashcompinit]
inline = "autoload -Uz bashcompinit && bashcompinit && complete -C x x"
