shell = "zsh"

[templates]
defer = """{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}"""

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.bashcompinit]
inline = "autoload -Uz bashcompinit && bashcompinit && complete -C x x"
